[package]
name = "cappuccino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
deflate = "1.0.0"
reqwest = "0.11"
toml = "0.5"
tokio = { version = "1", features = ["full"] }